export const ASSETS = {
  "/all-bookmark-white.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466534/all-bookmark-white_hu6cpq.svg",
  "/all-tools.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466536/all-tools_rpgodi.svg",
  "/all-tools-bg.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466535/all-tools-bg_qodp69.png",
  "/angle-down.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466535/angle-down_anwpbm.svg",
  "/arrow-right-black.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466534/arrow-right-black_xx2zhz.svg",
  "/arrow-right-white.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466534/arrow-right-white_kxfnje.svg",
  "/blog-1.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466538/blog-1_h9kmgc.svg",
  "/blog-2.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466539/blog-2_ickiue.svg",
  "/blog-3.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466535/blog-3_ly60nn.svg",
  "/case-studies-bg.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466540/case-studies-bg_odwkgw.png",
  "/checkmark-circle-black.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466540/checkmark-circle-black_omma8a.svg",
  "/checkmark-red.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740662246/checkmark-red_vuinof.svg",
  "/comment-white.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466535/comment-white_uuqkyb.svg",
  "/contact-us-header-bg.jpg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740549447/contact-us-header-bg_yyb0qp.jpg",
  "/drag-right-white.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466540/drag-right-white_pakml8.svg",
  "/facebook-black.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466536/facebook-black_rpnrw6.svg",
  "/favicon.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740467843/favicon_yak2bd.png",
  "/header-bg.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466542/header-bg_pkocht.png",
  "/header-grid.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466536/header-grid_dcxyhh.svg",
  "/how-it-works-bg.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466538/how-it-works-bg_zgtpt5.png",
  "/instagram-black.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466537/instagram-black_afgwh9.svg",
  "/job-search-white.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466541/job-search-white_efsbcm.svg",
  "/key-benefits-bg.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466538/key-benefits-bg_wxo33y.png",
  "/link-white.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466538/link-white_lf9dlc.svg",
  "/linkedin-black.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466538/linkedin-black_o9jgua.svg",
  "/logo.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466539/logo_iejeca.svg",
  "/manager-white.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466539/manager-white_cidnex.png",
  "/placeholder-logo.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466541/placeholder-logo_rjyfko.svg",
  "/pricing-bg.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466539/pricing-bg_trg5lo.png",
  "/professional-1.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466540/professional-1_ddlzxc.png",
  "/professional-2.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466540/professional-2_xxnc5b.png",
  "/professional-3.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466541/professional-3_juipvp.png",
  "/professional-4.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466541/professional-4_rbifjq.png",
  "/professional-5.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466543/professional-5_u3nf2i.png",
  "/professional-6.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466544/professional-6_taejdm.png",
  "/professional-7.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466544/professional-7_stbaqv.png",
  "/professional-8.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466545/professional-8_r5tfcm.png",
  "/professional-9.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466546/professional-9_x6lup8.png",
  "/professional-10.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466546/professional-10_n08t5c.png",
  "/professional-11.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466546/professional-11_oqozwl.png",
  "/professional-12.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466547/professional-12_vucjpi.png",
  "/qualified-workers.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466547/qualified-workers_mexpof.svg",
  "/rating-company.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466548/rating-company_bhbiel.png",
  "/ready-to-hire.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466549/ready-to-hire_jqrpxh.svg",
  "/ready-to-hire-bg.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740548164/ready-to-hire-bg_jqcmmf.png",
  "/responsive-candidates.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466549/responsive-candidates_j52xxt.svg",
  "/review-profile-1.png":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466549/review-profile-1_gw53r2.png",
  "/right-work.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466550/right-work_udtbwn.svg",
  "/search-white.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466550/search-white_tkzfc0.svg",
  "/star.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466550/star_abxrml.svg",
  "/twitter-black.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466551/twitter-black_qbpz5v.svg",
  "/why-image.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740466551/why-image_apfoyy.svg",
  "/youtube-black.svg":
    "https://res.cloudinary.com/yousafsabir/image/upload/v1740859070/youtube-black_y2dgvh.svg",
} as const;

export type AssetKey = keyof typeof ASSETS;
